## Python List

In [1]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [3]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [8]:
ary = []
for i in range(len(a)):
    ary.append(a[i] * b[i])
ary

[2, 12, 30, 56, 90]

In [9]:
[a[i] * b[i] for i in range(len(a))]

[2, 12, 30, 56, 90]

In [10]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [11]:
for i, j in zip(a,b):
    print(i * j)

2
12
30
56
90


In [12]:
type(a)

list

In [13]:
import numpy as np
na = np.array(a)
nb = np.array(b)

In [14]:
na

array([1, 3, 5, 7, 9])

In [15]:
type(na)

numpy.ndarray

In [17]:
na * nb

array([ 2, 12, 30, 56, 90])

In [19]:
nc = np.array([1,2,3])
na * nc 

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Numpy

In [20]:
na = np.array([1,2,3,4,5])

In [21]:
na[0]

1

In [22]:
na[-1]

5

In [23]:
na[0:3]

array([1, 2, 3])

In [24]:
a = [1,2,3,4,5]

In [25]:
ary = []
for e in a:
    if e > 3:
        ary.append(e)
ary

[4, 5]

In [27]:
[e for e in a if e > 3]

[4, 5]

In [28]:
na

array([1, 2, 3, 4, 5])

In [29]:
na > 3

array([False, False, False,  True,  True])

In [30]:
na[na > 3]

array([4, 5])

In [31]:
na = np.array([[1,2,3,4,5], [6,7,8,9,10]])
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
na[0,0]

1

In [33]:
na[0,:]

array([1, 2, 3, 4, 5])

In [34]:
na[:,0]

array([1, 6])

In [35]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [36]:
na = np.array([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na               

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [37]:
na = np.array([['name', 'gender', 'age'], ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na 


array([['name', 'gender', 'age'],
       ['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U6')

In [39]:
na[1:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U6')

In [41]:
import pandas as pd
df = pd.DataFrame([ ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df 

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [42]:
print(df)

       0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20


In [43]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20