## Python List

In [1]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [3]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [8]:
ary = []
for i in range(len(a)):
    ary.append(a[i] * b[i])
ary

[2, 12, 30, 56, 90]

In [9]:
[a[i] * b[i] for i in range(len(a))]

[2, 12, 30, 56, 90]

In [10]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [11]:
for i, j in zip(a,b):
    print(i * j)

2
12
30
56
90


In [12]:
type(a)

list

In [13]:
import numpy as np
na = np.array(a)
nb = np.array(b)

In [14]:
na

array([1, 3, 5, 7, 9])

In [15]:
type(na)

numpy.ndarray

In [17]:
na * nb

array([ 2, 12, 30, 56, 90])

In [19]:
nc = np.array([1,2,3])
na * nc 

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Numpy

In [20]:
na = np.array([1,2,3,4,5])

In [21]:
na[0]

1

In [22]:
na[-1]

5

In [23]:
na[0:3]

array([1, 2, 3])

In [24]:
a = [1,2,3,4,5]

In [25]:
ary = []
for e in a:
    if e > 3:
        ary.append(e)
ary

[4, 5]

In [27]:
[e for e in a if e > 3]

[4, 5]

In [28]:
na

array([1, 2, 3, 4, 5])

In [29]:
na > 3

array([False, False, False,  True,  True])

In [30]:
na[na > 3]

array([4, 5])

In [31]:
na = np.array([[1,2,3,4,5], [6,7,8,9,10]])
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
na[0,0]

1

In [33]:
na[0,:]

array([1, 2, 3, 4, 5])

In [34]:
na[:,0]

array([1, 6])

In [35]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [36]:
na = np.array([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na               

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [37]:
na = np.array([['name', 'gender', 'age'], ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na 


array([['name', 'gender', 'age'],
       ['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U6')

In [39]:
na[1:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U6')

In [41]:
import pandas as pd
df = pd.DataFrame([ ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df 

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [42]:
print(df)

       0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20


In [43]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

## Series

In [44]:
import pandas as pd
s = pd.Series([42000, 38000, 56000]) 
s


0    42000
1    38000
2    56000
dtype: int64

In [46]:
type(s)

pandas.core.series.Series

In [47]:
import pandas as pd
s = pd.Series([42000, 38000, 56000], index=['John', 'Marry', 'Sam']) 
s


John     42000
Marry    38000
Sam      56000
dtype: int64

In [48]:
s = pd.Series({'John':42000,'Marry':38000,'Sam':56000})
s


John     42000
Marry    38000
Sam      56000
dtype: int64

In [49]:
s[2]

56000

In [50]:
s[1:3]

Marry    38000
Sam      56000
dtype: int64

In [51]:
s['Sam']

56000

In [52]:
s[['Sam', 'John']]

Sam     56000
John    42000
dtype: int64

In [53]:
s< 40000

John     False
Marry     True
Sam      False
dtype: bool

In [54]:
s[s<40000]

Marry    38000
dtype: int64

In [56]:
s['Marry'] = 40000

In [57]:
s

John     42000
Marry    40000
Sam      56000
dtype: int64

In [60]:
s[s < 50000] = s[s < 50000] * 1.1

In [61]:
s

John     46200.0
Marry    44000.0
Sam      56000.0
dtype: float64

In [62]:
'Sam' in s

True

In [63]:
'Jane' in s

False

In [64]:
s

John     46200.0
Marry    44000.0
Sam      56000.0
dtype: float64

In [65]:
s * 0.8

John     36960.0
Marry    35200.0
Sam      44800.0
dtype: float64

In [66]:
import numpy as np
np.sqrt(s)

John     214.941853
Marry    209.761770
Sam      236.643191
dtype: float64

In [68]:
#print(dir(np))

In [69]:
s.max()

56000.0

In [70]:
s.min()

44000.0

In [71]:
s.mean()

48733.333333333336

In [72]:
s.median()

46200.00000000001

In [73]:
s.describe()

count        3.000000
mean     48733.333333
std       6388.531391
min      44000.000000
25%      45100.000000
50%      46200.000000
75%      51100.000000
max      56000.000000
dtype: float64

In [74]:
s2=s[['Marry', 'Jane']] + s[['John','Marry']] 
s2

Jane         NaN
John         NaN
Marry    88000.0
dtype: float64

In [75]:
np.nan

nan

In [76]:
s2

Jane         NaN
John         NaN
Marry    88000.0
dtype: float64

In [79]:
s2.isnull()

Jane      True
John      True
Marry    False
dtype: bool

In [81]:
s2.isnull().sum()

2

In [80]:
s2.notnull()

Jane     False
John     False
Marry     True
dtype: bool

## Pandas DataFrame

In [82]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df.columns = ['name', 'gender', 'age']
df



name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [83]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]], columns = ['name', 'gender', 'age'])
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [86]:
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F', 'age':21}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])


In [85]:
df2 = pd.DataFrame([{'name': 'QOO', 'gender': 'M', 'age':12},\
                   {'name':'Marry', 'gender': 'F'}])
df2

age gender   name
0  12.0      M    QOO
1   NaN      F  Marry

In [88]:
?df.head()

In [90]:
df.head()

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean

In [91]:
df.head(3)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom

In [92]:
df.tail(3)

age gender  name
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
age       6 non-null int64
gender    6 non-null object
name      6 non-null object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [94]:
df.describe()

age
count   6.000000
mean   26.833333
std     6.400521
min    20.000000
25%    21.500000
50%    26.000000
75%    32.000000
max    35.000000

In [95]:
df.dtypes

age        int64
gender    object
name      object
dtype: object

In [98]:
type(df)

pandas.core.frame.DataFrame

In [99]:
type(df['name'])

pandas.core.series.Series

In [102]:
type(df['name'].values)

numpy.ndarray

In [103]:
df[['name', 'age']]

name  age
0  frank   29
1   mary   23
2    tom   35
3    ted   33
4   jean   21
5   lisa   20

In [104]:
type(df[['name', 'age']])

pandas.core.frame.DataFrame

In [107]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [108]:
df[df['gender'] == 'M']

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [111]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [112]:
df['age'] > 30

0    False
1    False
2     True
3     True
4    False
5    False
Name: age, dtype: bool

In [110]:
(df['gender'] == 'M' ) & (df['age'] > 30)

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [113]:
df[(df['gender'] == 'M' ) & (df['age'] > 30)]

age gender name
2   35      M  tom
3   33      M  ted

In [114]:
df[(df['gender'] == 'M' ) | (df['age'] > 30)]

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [115]:
df['employee'] = True

In [116]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [117]:
del df['employee']

In [118]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [119]:
df['employee'] = True

In [120]:
?df.drop

In [121]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [122]:
df.drop('employee', axis = 1)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [123]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [124]:
#df = df.drop('employee', axis = 1)
df.drop('employee', axis = 1, inplace=True)

In [125]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [126]:
df.loc[5]

age         20
gender       F
name      lisa
Name: 5, dtype: object

In [127]:
df.loc[6]

KeyError: 'the label [6] is not in the [index]'

In [128]:
df.loc[6] = {'age':20,'gender':'F','name':'qoo'}
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa
6   20      F    qoo

In [129]:
df.loc[100] = {'age':200,'gender':'F','name':'qoo2'}
df

age gender   name
0     29      M  frank
1     23      F   mary
2     35      M    tom
3     33      M    ted
4     21      F   jean
5     20      F   lisa
6     20      F    qoo
100  200      F   qoo2

In [132]:
df = df.append(pd.DataFrame([{'age':120,'gender':'F','name':'qoo3'}]), ignore_index=True)


In [136]:
df.drop([6,7,8], inplace=True)

In [137]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [138]:
df['userid'] = range(101,107)

In [140]:
df.set_index('userid',inplace=True)

In [141]:
df

age gender   name
userid                   
101      29      M  frank
102      23      F   mary
103      35      M    tom
104      33      M    ted
105      21      F   jean
106      20      F   lisa

In [142]:
df.iloc[0]

age          29
gender        M
name      frank
Name: 101, dtype: object

In [143]:
df.iloc[1:3]

age gender  name
userid                  
102      23      F  mary
103      35      M   tom

In [146]:
df.iloc[1:3, [0,2]]

age  name
userid           
102      23  mary
103      35   tom

In [144]:
df.loc[[102,104,106]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [145]:
df.loc[[102,104,106], ['name', 'age']]

name  age
userid           
102     mary   23
104      ted   33
106     lisa   20

## Detect & Impute Missing Value

In [147]:
import pandas as pd
import numpy  as np
df = pd.DataFrame([\
                   ['frank', 'M',    np.nan], \
                   ['mary' , np.nan, np.nan], \
                   ['tom'  , 'M',    35], \
                   ['ted'  , 'M',    33], \
                   ['jean' , np.nan, 21], \
                   ['lisa' , 'F',    20]])
df.columns = ['name', 'gender', 'age']
df


name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [149]:
df['gender'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: gender, dtype: bool

In [150]:
df['gender'].notnull()

0     True
1    False
2     True
3     True
4    False
5     True
Name: gender, dtype: bool

In [151]:
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [152]:
df.name

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [155]:
df['name'].isnull().values.any()

False

In [156]:
df.isnull().values.any()

True

In [157]:
df.isnull().sum()

name      0
gender    2
age       2
dtype: int64

In [158]:
df.isnull().sum().sum()

4

In [159]:
df

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [161]:
#df.dropna(inplace=True)
df.dropna()

name gender   age
2   tom      M  35.0
3   ted      M  33.0
5  lisa      F  20.0

In [162]:
df.dropna(how= 'all')

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [163]:
df.dropna(thresh=2)


name gender   age
0  frank      M   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [164]:
df['employee'] = np.nan

In [166]:
df

name gender   age  employee
0  frank      M   NaN       NaN
1   mary    NaN   NaN       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean    NaN  21.0       NaN
5   lisa      F  20.0       NaN

In [169]:
df.dropna(how = 'all', axis = 1)

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [170]:
df

name gender   age  employee
0  frank      M   NaN       NaN
1   mary    NaN   NaN       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean    NaN  21.0       NaN
5   lisa      F  20.0       NaN

In [171]:
df.fillna(0)

name gender   age  employee
0  frank      M   0.0       0.0
1   mary      0   0.0       0.0
2    tom      M  35.0       0.0
3    ted      M  33.0       0.0
4   jean      0  21.0       0.0
5   lisa      F  20.0       0.0

In [172]:
df['age'].fillna(0)
#df['age'] = df['age'].fillna(0)

0     0.0
1     0.0
2    35.0
3    33.0
4    21.0
5    20.0
Name: age, dtype: float64

In [176]:
df['age'].fillna(df['age'].mean())

0    27.25
1    27.25
2    35.00
3    33.00
4    21.00
5    20.00
Name: age, dtype: float64

In [178]:
# select gender, avg(age) from df group gender
df.groupby('gender')['age'].mean()

gender
F    20.0
M    34.0
Name: age, dtype: float64

In [179]:
df.groupby('gender')['age'].transform('mean')

0    34.0
1     NaN
2    34.0
3    34.0
4     NaN
5    20.0
Name: age, dtype: float64

In [181]:
df['age'] = df.groupby('gender')['age'].transform('mean')
df

name gender   age  employee
0  frank      M  34.0       NaN
1   mary    NaN   NaN       NaN
2    tom      M  34.0       NaN
3    ted      M  34.0       NaN
4   jean    NaN   NaN       NaN
5   lisa      F  20.0       NaN

In [182]:
df.fillna(method='pad')

name gender   age  employee
0  frank      M  34.0       NaN
1   mary      M  34.0       NaN
2    tom      M  34.0       NaN
3    ted      M  34.0       NaN
4   jean      M  34.0       NaN
5   lisa      F  20.0       NaN

In [183]:
df.fillna(method='bfill', limit=2)


name gender   age  employee
0  frank      M  34.0       NaN
1   mary      M  34.0       NaN
2    tom      M  34.0       NaN
3    ted      M  34.0       NaN
4   jean      F  20.0       NaN
5   lisa      F  20.0       NaN

In [ ]:
df2 = pd.DataFrame([[1, 870],\
                    [2, 900],\
                    [np.nan, np.nan],\
                    [4, 950],\
                    [5,1080],\
                    [6,1200]])
df2.columns = ['time', 'val']
df2.interpolate()


## Data Transformation

In [3]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/cathaybkpython/master/data/rent_591_sample.csv', index_col=0 )

In [5]:
df.head()

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   
39  https://rent.591.com.tw/rent-detail-2375928.html  2017-05-10   
65  https://rent.591.com.tw/rent-detail-2061829.html  2017-05-08   

                   title      address floor_info      price     layout  \
11      政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10,000元/月        NaN   
15   台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25,000元/月  4房3廳3衛3陽臺   
20   小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70,000元/月  7房2廳2衛1陽臺   
39   環境單純，生活機能佳，近市中心交通便利    台北市松山區吉祥路      2F/4F   8,000元/月        NaN   
65  房間分租/獨立衛浴/環境舒適~近天母三越   台北市士林區天母東路      3F/5F  14,000元/月        NaN   

    building_area building_use   latitude   longitude  
11           6.00      公寓/獨立套房  24.988698  121.574008  
15          78.00    電梯大樓/整層住家  25.140992  121.508139  
20          66.35    電梯大樓/整層住家  25.051868  121.553830  
39           6.00     透天厝/分租套房  25.049546  121.562708  
65          26.00        公寓/辦公  25.118543  121.534280

In [8]:
(df['building_area'] / 0.3025).head()

11     19.834711
15    257.851240
20    219.338843
39     19.834711
65     85.950413
Name: building_area, dtype: float64

In [10]:
import numpy as np
np.sqrt(df['building_area']).head()

11    2.449490
15    8.831761
20    8.145551
39    2.449490
65    5.099020
Name: building_area, dtype: float64

In [15]:
(df['address'] + '-' + df['price']).head()

11    台北市文山區指南路二段-10,000元/月
15      台北市北投區新民路-25,000元/月
20      台北市松山區北寧路-70,000元/月
39       台北市松山區吉祥路-8,000元/月
65     台北市士林區天母東路-14,000元/月
dtype: object

In [16]:
df['square_feet'] = df['building_area'] / 0.3025

In [18]:
df.head()

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   
39  https://rent.591.com.tw/rent-detail-2375928.html  2017-05-10   
65  https://rent.591.com.tw/rent-detail-2061829.html  2017-05-08   

                   title      address floor_info      price     layout  \
11      政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10,000元/月        NaN   
15   台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25,000元/月  4房3廳3衛3陽臺   
20   小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70,000元/月  7房2廳2衛1陽臺   
39   環境單純，生活機能佳，近市中心交通便利    台北市松山區吉祥路      2F/4F   8,000元/月        NaN   
65  房間分租/獨立衛浴/環境舒適~近天母三越   台北市士林區天母東路      3F/5F  14,000元/月        NaN   

    building_area building_use   latitude   longitude  square_feet  
11           6.00      公寓/獨立套房  24.988698  121.574008    19.834711  
15          78.00    電梯大樓/整層住家  25.140992  121.508139   257.851240  
20          66.35    電梯大樓/整層住家  25.051868  121.553830   219.338843  
39           6.00     透天厝/分租套房  25.049546  121.562708    19.834711  
65          26.00        公寓/辦公  25.118543  121.534280    85.950413

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17180 entries, 11 to 70314
Data columns (total 12 columns):
detail_url       17180 non-null object
search_date      17180 non-null object
title            17180 non-null object
address          17179 non-null object
floor_info       16806 non-null object
price            17180 non-null object
layout           5821 non-null object
building_area    17180 non-null float64
building_use     15586 non-null object
latitude         17179 non-null float64
longitude        17179 non-null float64
square_feet      17180 non-null float64
dtypes: float64(4), object(8)
memory usage: 2.3+ MB


In [40]:
df = df[df['price'].str.contains('元/月')]

In [41]:
p = '25,000元/月'
int(p.replace('元/月', '').replace(',', ''))

25000

In [42]:
def normalizePrice(ele):
    try:
        return int(ele.replace('元/月', '').replace(',', ''))
    except:
        return np.nan

In [43]:
normalizePrice('10,000元/月')

10000

In [44]:
df['price'].map(normalizePrice).head()

11    10000
15    25000
20    70000
39     8000
65    14000
Name: price, dtype: int64

In [45]:
df['price'].map(lambda ele : int(ele.replace('元/月', '').replace(',', '')) if '元/月' in ele else np.nan).head()

11    10000
15    25000
20    70000
39     8000
65    14000
Name: price, dtype: int64

In [46]:
df['price'] = df['price'].map(lambda ele : int(ele.replace('元/月', '').replace(',', '')) if '元/月' in ele else np.nan).head()

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [49]:
df.head(3)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   

                  title      address floor_info    price     layout  \
11     政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10000.0        NaN   
15  台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25000.0  4房3廳3衛3陽臺   
20  小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70000.0  7房2廳2衛1陽臺   

    building_area building_use   latitude   longitude  square_feet  
11           6.00      公寓/獨立套房  24.988698  121.574008    19.834711  
15          78.00    電梯大樓/整層住家  25.140992  121.508139   257.851240  
20          66.35    電梯大樓/整層住家  25.051868  121.553830   219.338843

In [53]:
(df['price'] / df['building_area']).mean()

982.7971325333796

In [54]:
df = pandas.DataFrame(\
[\
   [60,70,50],\
   [80,79,68],\
   [63,66,82]], \
  columns = ['First', 'Second', 'Third'])


In [55]:
df

First  Second  Third
0     60      70     50
1     80      79     68
2     63      66     82

In [57]:
df.apply(lambda e: e.max() - e.min(), axis = 1)

0    20
1    12
2    19
dtype: int64

In [58]:
df.apply(lambda e: e.max() - e.min(), axis = 0)

First     20
Second    13
Third     32
dtype: int64

In [62]:
df = pandas.DataFrame(\
[\
   [60,70,50],\
   [80,np.nan,68],\
   [63,66,82]], \
  columns = ['First', 'Second', 'Third'])


In [63]:
df

First  Second  Third
0     60    70.0     50
1     80     NaN     68
2     63    66.0     82

In [64]:
import numpy as np
df.applymap(lambda e: '-' if pandas.isnull(e) else e)


First Second  Third
0     60     70     50
1     80      -     68
2     63     66     82

## Time Conversion

In [65]:
from datetime import datetime
current_time = datetime.now()
current_time

datetime.datetime(2018, 12, 4, 14, 17, 6, 781999)

In [66]:
type(current_time)

datetime.datetime

In [67]:
# convert datetime obj to str
current_time.strftime('%Y-%m-%d')

'2018-12-04'

In [68]:
from __future__ import print_function
#print 2
print(2)

2


In [70]:
# convert string to datetime
datetime.strptime('2018-12-01', '%Y-%m-%d')

datetime.datetime(2018, 12, 1, 0, 0)

In [73]:
t1 = datetime.strptime('2016/05/20', '%Y/%m/%d')
current_time - t1

datetime.timedelta(928, 51426, 781999)

In [74]:
from datetime import timedelta
t1 = datetime.strptime('2018-12-01', '%Y-%m-%d') 
t1 - timedelta(days = 1)

datetime.datetime(2018, 11, 30, 0, 0)

In [78]:
current_time
for i in range(10):
    dt = current_time- timedelta(days = i)
    print(dt.strftime('%Y-%m-%d'))

2018-12-04
2018-12-03
2018-12-02
2018-12-01
2018-11-30
2018-11-29
2018-11-28
2018-11-27
2018-11-26
2018-11-25


In [79]:
from time import mktime
mktime(current_time.timetuple())

1543904226.0

In [80]:
datetime.fromtimestamp(1492859823)

datetime.datetime(2017, 4, 22, 19, 17, 3)

In [81]:
df

First  Second  Third
0     60    70.0     50
1     80     NaN     68
2     63    66.0     82

In [82]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/cathaybkpython/master/data/rent_591_sample.csv', index_col=0 )

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17180 entries, 11 to 70314
Data columns (total 11 columns):
detail_url       17180 non-null object
search_date      17180 non-null object
title            17180 non-null object
address          17179 non-null object
floor_info       16806 non-null object
price            17180 non-null object
layout           5821 non-null object
building_area    17180 non-null float64
building_use     15586 non-null object
latitude         17179 non-null float64
longitude        17179 non-null float64
dtypes: float64(3), object(8)
memory usage: 1.6+ MB


In [86]:
df = df[df['price'].str.contains('元/月')]

In [88]:
df['search_date'] = pandas.to_datetime(df['search_date'], format = '%Y-%m-%d')

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17175 entries, 11 to 70314
Data columns (total 11 columns):
detail_url       17175 non-null object
search_date      17175 non-null datetime64[ns]
title            17175 non-null object
address          17175 non-null object
floor_info       16801 non-null object
price            17175 non-null object
layout           5819 non-null object
building_area    17175 non-null float64
building_use     15583 non-null object
latitude         17175 non-null float64
longitude        17175 non-null float64
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 2.2+ MB


In [92]:
df['search_date'].describe()

count                   17175
unique                      8
top       2017-05-13 00:00:00
freq                     6152
first     2017-05-08 00:00:00
last      2017-05-15 00:00:00
Name: search_date, dtype: object

In [94]:
df[df['search_date'] > '2017-05-10'].head(3)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   

                  title      address floor_info      price     layout  \
11     政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10,000元/月        NaN   
15  台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25,000元/月  4房3廳3衛3陽臺   
20  小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70,000元/月  7房2廳2衛1陽臺   

    building_area building_use   latitude   longitude  
11           6.00      公寓/獨立套房  24.988698  121.574008  
15          78.00    電梯大樓/整層住家  25.140992  121.508139  
20          66.35    電梯大樓/整層住家  25.051868  121.553830

In [95]:
df.to_csv('rent_591_sample.csv', encoding='utf-8-sig')

## Dummy Variable

In [98]:
pandas.get_dummies(df['building_use']).head(3)

倉庫/其他  公寓/住辦  公寓/其他  公寓/分租套房  公寓/店面  公寓/整層住家  公寓/獨立套房  公寓/辦公  公寓/雅房  \
11      0      0      0        0      0        0        1      0      0   
15      0      0      0        0      0        0        0      0      0   
20      0      0      0        0      0        0        0      0      0   

    別墅/住辦   ...     透天厝/辦公  透天厝/雅房  電梯大樓/住辦  電梯大樓/其他  電梯大樓/分租套房  電梯大樓/店面  \
11      0   ...          0       0        0        0          0        0   
15      0   ...          0       0        0        0          0        0   
20      0   ...          0       0        0        0          0        0   

    電梯大樓/整層住家  電梯大樓/獨立套房  電梯大樓/辦公  電梯大樓/雅房  
11          0          0        0        0  
15          1          0        0        0  
20          1          0        0        0  

[3 rows x 32 columns]

In [100]:
df2 = pandas.concat([df, pandas.get_dummies(df['building_use'])], axis=1)
df2.head(3)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   

                  title      address floor_info      price     layout  \
11     政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10,000元/月        NaN   
15  台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25,000元/月  4房3廳3衛3陽臺   
20  小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70,000元/月  7房2廳2衛1陽臺   

    building_area building_use   latitude   ...     透天厝/辦公  透天厝/雅房  電梯大樓/住辦  \
11           6.00      公寓/獨立套房  24.988698   ...          0       0        0   
15          78.00    電梯大樓/整層住家  25.140992   ...          0       0        0   
20          66.35    電梯大樓/整層住家  25.051868   ...          0       0        0   

    電梯大樓/其他  電梯大樓/分租套房  電梯大樓/店面  電梯大樓/整層住家  電梯大樓/獨立套房  電梯大樓/辦公  電梯大樓/雅房  
11        0          0        0          0          0        0        0  
15        0          0        0          1          0        0        0  
20        0          0        0          1          0        0        0  

[3 rows x 43 columns]

In [102]:
df.drop('building_use', axis=1).head(1)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   

               title      address floor_info      price layout  building_area  \
11  政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10,000元/月    NaN            6.0   

     latitude   longitude  
11  24.988698  121.574008

In [103]:
df['price'] = df['price'].map(lambda ele : int(ele.replace('元/月', '').replace(',', '')) if '元/月' in ele else np.nan).head()

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [108]:
df2 = df.pivot_table(index='search_date', columns='building_use', values='price', aggfunc=sum)
df2.head()


building_use  公寓/獨立套房    公寓/辦公  透天厝/分租套房  電梯大樓/整層住家
search_date                                        
2017-05-08        NaN  14000.0       NaN        NaN
2017-05-09        NaN      NaN       NaN        NaN
2017-05-10        NaN      NaN    8000.0        NaN
2017-05-11        NaN      NaN       NaN        NaN
2017-05-12        NaN      NaN       NaN        NaN

In [107]:
df3 = df.pivot_table(index='building_use', columns='search_date', values='price', aggfunc=sum)
df3.head()


search_date   2017-05-08  2017-05-10  2017-05-13  2017-05-14
building_use                                                
倉庫/其他                NaN         NaN         NaN         NaN
公寓/住辦                NaN         NaN         NaN         NaN
公寓/其他                NaN         NaN         NaN         NaN
公寓/分租套房              NaN         NaN         NaN         NaN
公寓/店面                NaN         NaN         NaN         NaN

In [110]:
'公寓/分租套房'.split('/')[0]

'公寓'

In [111]:
'公寓/分租套房'.split('/')[1]

'分租套房'

In [112]:
df['btype'] = df['building_use'].map(lambda e: str(e).split('/')[0])


/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [113]:
df['buse']  = df['building_use'].map(lambda e: str(e).split('/')[1] if len(str(e).split('/'))> 1 else None)


/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [114]:
df.head(3)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   

                  title      address floor_info    price     layout  \
11     政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10000.0        NaN   
15  台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25000.0  4房3廳3衛3陽臺   
20  小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70000.0  7房2廳2衛1陽臺   

    building_area building_use   latitude   longitude btype  buse  
11           6.00      公寓/獨立套房  24.988698  121.574008    公寓  獨立套房  
15          78.00    電梯大樓/整層住家  25.140992  121.508139  電梯大樓  整層住家  
20          66.35    電梯大樓/整層住家  25.051868  121.553830  電梯大樓  整層住家

In [115]:
df_multi_idx = df.pivot_table(index=['btype', 'buse'], columns='search_date', values='price', aggfunc=sum) 
df_multi_idx

search_date  2017-05-08  2017-05-10  2017-05-13  2017-05-14
btype buse                                                 
倉庫    其他            NaN         NaN         NaN         NaN
公寓    住辦            NaN         NaN         NaN         NaN
      其他            NaN         NaN         NaN         NaN
      分租套房          NaN         NaN         NaN         NaN
      店面            NaN         NaN         NaN         NaN
      整層住家          NaN         NaN         NaN         NaN
      獨立套房          NaN         NaN         NaN     10000.0
      辦公        14000.0         NaN         NaN         NaN
      雅房            NaN         NaN         NaN         NaN
別墅    住辦            NaN         NaN         NaN         NaN
      其他            NaN         NaN         NaN         NaN
      分租套房          NaN         NaN         NaN         NaN
      整層住家          NaN         NaN         NaN         NaN
      獨立套房          NaN         NaN         NaN         NaN
      雅房            NaN         NaN         NaN         NaN
廠辦    其他            NaN         NaN         NaN         NaN
透天厝   住辦            NaN         NaN         NaN         NaN
      其他            NaN         NaN         NaN         NaN
      分租套房          NaN      8000.0         NaN         NaN
      店面            NaN         NaN         NaN         NaN
      整層住家          NaN         NaN         NaN         NaN
      獨立套房          NaN         NaN         NaN         NaN
      辦公            NaN         NaN         NaN         NaN
      雅房            NaN         NaN         NaN         NaN
電梯大樓  住辦            NaN         NaN         NaN         NaN
      其他            NaN         NaN         NaN         NaN
      分租套房          NaN         NaN         NaN         NaN
      店面            NaN         NaN         NaN         NaN
      整層住家          NaN         NaN     70000.0     25000.0
      獨立套房          NaN         NaN         NaN         NaN
      辦公            NaN         NaN         NaN         NaN
      雅房            NaN         NaN         NaN         NaN

In [116]:
df_wide = df_multi_idx.unstack()
df_wide.head()


search_date 2017-05-08                                     2017-05-10     ...  \
buse                住辦  其他 分租套房  店面 整層住家 獨立套房       辦公  雅房         住辦  其他 ...   
btype                                                                     ...   
倉庫                 NaN NaN  NaN NaN  NaN  NaN      NaN NaN        NaN NaN ...   
公寓                 NaN NaN  NaN NaN  NaN  NaN  14000.0 NaN        NaN NaN ...   
別墅                 NaN NaN  NaN NaN  NaN  NaN      NaN NaN        NaN NaN ...   
廠辦                 NaN NaN  NaN NaN  NaN  NaN      NaN NaN        NaN NaN ...   
透天厝                NaN NaN  NaN NaN  NaN  NaN      NaN NaN        NaN NaN ...   

search_date 2017-05-13     2017-05-14                                     
buse                辦公  雅房         住辦  其他 分租套房  店面 整層住家     獨立套房  辦公  雅房  
btype                                                                     
倉庫                 NaN NaN        NaN NaN  NaN NaN  NaN      NaN NaN NaN  
公寓                 NaN NaN        NaN NaN  NaN NaN  NaN  10000.0 NaN NaN  
別墅                 NaN NaN        NaN NaN  NaN NaN  NaN      NaN NaN NaN  
廠辦                 NaN NaN        NaN NaN  NaN NaN  NaN      NaN NaN NaN  
透天厝                NaN NaN        NaN NaN  NaN NaN  NaN      NaN NaN NaN  

[5 rows x 32 columns]

In [117]:
df_long = df_wide.stack()
df_long.head()


search_date  2017-05-08  2017-05-10  2017-05-13  2017-05-14
btype buse                                                 
公寓    獨立套房          NaN         NaN         NaN     10000.0
      辦公        14000.0         NaN         NaN         NaN
透天厝   分租套房          NaN      8000.0         NaN         NaN
電梯大樓  整層住家          NaN         NaN     70000.0     25000.0

## Regular Expression

In [118]:
a = 'my phone number is 0912333444'
'0912333444' in a

True

In [123]:
n = '5'

In [124]:
import re

In [125]:
re.search('3', n)

In [126]:
# []: match any character within []
re.search('[35]', n)

<_sre.SRE_Match object; span=(0, 1), match='5'>

In [127]:
re.search('[0123456789]', n)

<_sre.SRE_Match object; span=(0, 1), match='5'>

In [128]:
# - :continue => [0123456789] : [0-9]
re.search('[0-9]', n)

<_sre.SRE_Match object; span=(0, 1), match='5'>

In [129]:
# \d :digit => [0-9] : \d
re.search('\d', n)

<_sre.SRE_Match object; span=(0, 1), match='5'>

In [130]:
s = 'w'

In [131]:
re.search('[abcdefghijklmnopqrstuvwxyz]', s)

<_sre.SRE_Match object; span=(0, 1), match='w'>

In [132]:
re.search('[a-z]', s)

<_sre.SRE_Match object; span=(0, 1), match='w'>

In [133]:
s = 'R'

In [134]:
re.search('[a-z]', s)

In [135]:
re.search('[a-zA-Z]', s)

<_sre.SRE_Match object; span=(0, 1), match='R'>

In [136]:
n = '7'
re.search('[a-zA-Z]', n)

In [137]:
re.search('[a-zA-Z0-9]', n)

<_sre.SRE_Match object; span=(0, 1), match='7'>

In [138]:
# \w : match word => [a-zA-Z0-9] : \w 
re.search('\w', n)

<_sre.SRE_Match object; span=(0, 1), match='7'>

In [139]:
s = '&'
re.search('\w', s)

In [140]:
# . : match any character => \w\d!@$#^* : .
re.search('.', s)

<_sre.SRE_Match object; span=(0, 1), match='&'>

In [141]:
s = 'apple'
re.search('\w', s)

<_sre.SRE_Match object; span=(0, 1), match='a'>

In [142]:
re.search('\w\w\w\w\w', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [143]:
# {n} : match exact n characters
re.search('\w{5}', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [144]:
# {m,n} : match at least m characters, at most n characters
re.search('\w{3,8}', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [145]:
re.search('\w{0,}', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [146]:
re.search('\w{1,}', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [147]:
# * => {0,}
re.search('\w*', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [148]:
# + => {1,}
re.search('\w+', s)

<_sre.SRE_Match object; span=(0, 5), match='apple'>

In [149]:
phones = ['0912345678', '0912-345-678','0912-345678', '009812380918309183018301830830']

In [154]:
for p in phones:
    #print(re.search('09\d{8}', p))
    #print(re.search('09\d{2}-{0,1}\d{3}-{0,1}\d{3}', p))
    
    # ? => {0,1}
    #print(re.search('09\d{2}-?\d{3}-?\d{3}', p))
    
    # ^ : match the begin, $: match the end
    print(re.search('^09\d{2}-?\d{3}-?\d{3}$', p))
    

<_sre.SRE_Match object; span=(0, 10), match='0912345678'>
<_sre.SRE_Match object; span=(0, 12), match='0912-345-678'>
<_sre.SRE_Match object; span=(0, 11), match='0912-345678'>
None


In [155]:
import re 
m = re.match(r"(\w+)@(\w+)", "david@largidata.com") 
print(m.groups())


('david', 'largidata')


In [156]:
m.group(1)

'david'

In [157]:
m.group(2)

'largidata'

In [158]:
import re 
m = re.match(r"(\w+)@([\w.]+)", "david@largidata.com") 
print(m.groups())


('david', 'largidata.com')


In [159]:
m = re.match(r"(\d+)\.(\d+)", "1999.5") 
print(m.groups())


('1999', '5')


In [160]:
m = re.match(r"(?P<first_name>\w+) (?P<last_name>\w+)", "David Chiu") 
print(m.group('first_name'), m.group('last_name'))


David Chiu


In [161]:
print(m.group(1), m.group(2))

David Chiu


In [162]:
str1 = 'scp file.txt root@10.0.0.1:./' 
m=re.search('^scp ([\w\.]+) (\w+)@([\w\.]+):(.+)',str1) 
if m: 
    print(m.group(1), m.group(2), m.group(3), m.group(4))


file.txt root 10.0.0.1 ./


In [165]:
df[['room', 'living_room', 'bathroom', 'balcony']] =  df['layout'].str.extract('(\d+)房(\d+)廳(\d+)衛(\d+)陽臺')

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.
/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pandas/core/frame.py:2352: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


In [170]:
df['address']

11        台北市文山區指南路二段
15          台北市北投區新民路
20          台北市松山區北寧路
39          台北市松山區吉祥路
65         台北市士林區天母東路
71       台北市士林區中山北路七段
72        台北市大安區仁愛路四段
78          台北市內湖區瑞光路
79        台北市南港區南港路二段
84          台北市大安區通化街
98          台北市內湖區文德路
100         台北市中山區天祥路
101         台北市信義區吳興街
121      台北市信義區忠孝東路五段
123         台北市文山區景華街
124      台北市大安區敦化南路二段
125       台北市大安區信義路三段
130         台北市中山區龍江路
136         台北市萬華區青年路
140       台北市大安區安和路二段
150        台北市北投區天母西路
151         台北市大安區臥龍街
154      台北市中正區忠孝西路一段
155      台北市中正區羅斯福路一段
156      台北市松山區民權東路三段
168      台北市萬華區和平西路三段
169       台北市大安區安和路二段
186         台北市士林區文昌路
188       台北市信義區基隆路二段
194        台北市大同區長安西路
             ...     
70188       台北市內湖區江南街
70190     台北市松山區八德路三段
70192     台北市萬華區西園路二段
70206       台北市大安區麗水街
70210       台北市中山區吉林路
70219      台北市中山區樂群三路
70223     台北市北投區三合街一段
70227       台北市大同區五原路
70233       台北市萬華區康定路
70237       台北市內湖區康樂街
70239     台北市大安區濟南路三段
70242       台北市信義區吳興街
70243     台北市內湖區康寧路三段
70247     台北市文山區興隆路三段
70248    台

In [173]:
df[['city', 'area', 'road']] = df['address'].str.extract('(.+市)(.+區)(.+[路街])')

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.
/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pandas/core/frame.py:2352: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


In [174]:
df.head(3)

detail_url search_date  \
11  https://rent.591.com.tw/rent-detail-1944741.html  2017-05-14   
15  https://rent.591.com.tw/rent-detail-2037235.html  2017-05-14   
20  https://rent.591.com.tw/rent-detail-1954040.html  2017-05-13   

                  title      address floor_info    price     layout  \
11     政大靜巷優質(女)套房，可住雙人  台北市文山區指南路二段      5F/5F  10000.0        NaN   
15  台北市北投新民路捷運溫泉78坪雙拼美廈    台北市北投區新民路      2F/9F  25000.0  4房3廳3衛3陽臺   
20  小巨捷運敦化學區樓中樓可三代同堂兼辦公    台北市松山區北寧路      5F/7F  70000.0  7房2廳2衛1陽臺   

    building_area building_use   latitude   longitude btype  buse room  \
11           6.00      公寓/獨立套房  24.988698  121.574008    公寓  獨立套房  NaN   
15          78.00    電梯大樓/整層住家  25.140992  121.508139  電梯大樓  整層住家    4   
20          66.35    電梯大樓/整層住家  25.051868  121.553830  電梯大樓  整層住家    7   

   living_room bathroom balcony city area road  
11         NaN      NaN     NaN  台北市  文山區  指南路  
15           3        3       3  台北市  北投區  新民路  
20           2        2       1  台北市  松山區  北寧路

In [175]:
! pip install pdfminer3k

You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [176]:
from pdfminer.pdfparser import PDFParser, PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine

s = ''
fp = open('swim.pdf', 'rb')
parser = PDFParser(fp)
doc = PDFDocument()
parser.set_document(doc)
doc.set_parser(parser)
doc.initialize('')
rsrcmgr = PDFResourceManager()
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
# Process each page contained in the document.
for page in doc.get_pages():
    interpreter.process_page(page)
    layout = device.get_result()
    for lt_obj in layout:
        #print(lt_obj)
        if isinstance(lt_obj, LTTextBox) or isinstance(lt_obj, LTTextLine):
            s = s + lt_obj.get_text()


In [180]:
import re
phones = re.findall('09\d{8}',s)

In [182]:
emails = re.findall('[\w.]+@[\w.]+',s)

In [187]:
lastnames = '''
陳，林，黃，張，李，王，吳，劉，蔡，楊，
許，鄭，謝，郭，洪，曾，邱，廖，賴，周，
徐，蘇，葉，莊，呂，江，何，蕭，羅，高，
簡，朱，鍾，施，游，詹，沈，彭，胡，余，
盧，潘，顏，梁，趙，柯，翁，魏，方，孫，
張簡，戴，范，歐陽，宋，鄧，杜，侯，曹，薛，
傅，丁，溫，紀，范姜，蔣，歐，藍，連，唐，
馬，董，石，卓，程，姚，康，馮，古，姜，
湯，汪，白，田，涂，鄒，巫，尤，鐘，龔，
嚴，韓，黎，阮，袁，童，陸，金，錢，邵
'''
''.join([e.strip() for e in lastnames.strip().split('，')])

'陳林黃張李王吳劉蔡楊許鄭謝郭洪曾邱廖賴周徐蘇葉莊呂江何蕭羅高簡朱鍾施游詹沈彭胡余盧潘顏梁趙柯翁魏方孫張簡戴范歐陽宋鄧杜侯曹薛傅丁溫紀范姜蔣歐藍連唐馬董石卓程姚康馮古姜湯汪白田涂鄒巫尤鐘龔嚴韓黎阮袁童陸金錢邵'

In [190]:
names = re.findall('[陳林黃張李王吳劉蔡楊許鄭謝郭洪曾邱廖賴周徐蘇葉莊呂江何蕭羅高簡朱鍾施游詹沈彭胡余盧潘顏梁趙柯翁魏方孫張簡戴范歐陽宋鄧杜侯曹薛傅丁溫紀范姜蔣歐藍連唐馬董石卓程姚康馮古姜湯汪白田涂鄒巫尤鐘龔嚴韓黎阮袁童陸金錢邵][\u4e00-\u9fa5]{2}', s)